//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqLibTests.Properties
{

  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Resources
  {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
      get
      {
        if (object.ReferenceEquals(resourceMan, null))
        {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqLibTests.Properties.Resources", typeof(Resources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
      get
      {
        return resourceCulture;
      }
      set
      {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to A:Split1D-1 D:5,4 
    ///~~SOA~~
    ///1,2,3,4
    ///2,3,4,5
    ///3,4,5,6
    ///4,5,6,7
    ///5,6,7,8
    ///~~EOA~~
    ///
    ///A:Split1D-2 D:3,3 
    ///~~SOA~~
    ///1,2,3
    ///3,4,5
    ///5,6,7
    ///~~EOA~~.
    /// </summary>
    internal static string ExpectedArrayData
    {
      get
      {
        return ResourceManager.GetString("ExpectedArrayData", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to I&apos;ve heard there was a secret chord
    ///That David played, and it pleased the Lord
    ///But you don&apos;t really care for music, do you?
    ///It goes like this
    ///The fourth, the fifth
    ///The minor fall, the major lift
    ///The baffled king composing Hallelujah
    /// 
    ///Hallelujah, Hallelujah
    ///Hallelujah, Hallelujah
    /// 
    ///Your faith was strong but you needed proof
    ///You saw her bathing on the roof
    ///Her beauty in the moonlight overthrew you
    ///She tied you to a kitchen chair
    ///She broke your throne, and she cut your hair
    ///And from your lips  [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string Hallelujah1
    {
      get
      {
        return ResourceManager.GetString("Hallelujah1", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to I&apos;ve heard there was a secret chord
    ///That David played, and it pleased the Lord
    ///But you don&apos;t really care for music, do you?
    ///It goes like this
    ///The fourth, the fifth
    ///The minor fall, the major lift
    ///The baffled king composing Hallelujah
    /// 
    ///Hallelujah, Hallelujah
    ///Hallelujah, Hallelujah
    /// 
    ///YOUR FAITH WAS STRONG BUT YOU NEEDED PROOF
    ///You saw her bathing on the roof
    ///Her beauty in the moonlight overthrew you
    ///She tied you to a kitchen chair
    ///She broke your throne, and she cut your hair
    ///AND FROM YOUR LIPS  [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string Hallelujah2
    {
      get
      {
        return ResourceManager.GetString("Hallelujah2", resourceCulture);
      }
    }
  }
}
